var valo63=
document.getElementById("v63").innerHTML=valo63;
var valo64=
document.getElementById("v64").innerHTML=valo64;
var valo65=
document.getElementById("v65").innerHTML=valo65;
var valo66=
document.getElementById("v66").innerHTML=valo66;
var valo67=
document.getElementById("v67").innerHTML=valo67;
var valo68=
document.getElementById("v68").innerHTML=valo68;
var valo69=
document.getElementById("v69").innerHTML=valo69;
var valo70=
document.getElementById("v70").innerHTML=valo70;
var valo71=
document.getElementById("v71").innerHTML=valo71;