var valo81=
document.getElementById("v81").innerHTML=valo81;
var valo82=
document.getElementById("v82").innerHTML=valo82;
var valo83=
document.getElementById("v83").innerHTML=valo83;
var valo84=
document.getElementById("v84").innerHTML=valo84;
var valo85=
document.getElementById("v85").innerHTML=valo85;
var valo86=
document.getElementById("v86").innerHTML=valo86;
var valo87=
document.getElementById("v87").innerHTML=valo87;
var valo88=
document.getElementById("v88").innerHTML=valo88;
var valo89=
document.getElementById("v89").innerHTML=valo89;
var valo89=
document.getElementById("v90").innerHTML=valo89;
