var valo45=
document.getElementById("v45").innerHTML=valo45;
var valo46=
document.getElementById("v46").innerHTML=valo46;
var valo47=
document.getElementById("v47").innerHTML=valo47;
var valo48=
document.getElementById("v48").innerHTML=valo48;
var valo49=
document.getElementById("v49").innerHTML=valo49;
var valo50=
document.getElementById("v50").innerHTML=valo50;
var valo51=
document.getElementById("v51").innerHTML=valo51;
var valo52=
document.getElementById("v52").innerHTML=valo52;
var valo53=
document.getElementById("v53").innerHTML=valo53;