var valo54=
document.getElementById("v54").innerHTML=valo54;
var valo55=
document.getElementById("v55").innerHTML=valo55;
var valo56=
document.getElementById("v56").innerHTML=valo56;
var valo57=
document.getElementById("v57").innerHTML=valo57;
var valo58=
document.getElementById("v58").innerHTML=valo58;
var valo59=
document.getElementById("v59").innerHTML=valo59;
var valo60=
document.getElementById("v60").innerHTML=valo60;
var valo61=
document.getElementById("v61").innerHTML=valo61;
var valo62=
document.getElementById("v62").innerHTML=valo62;