var valo37=
document.getElementById("v37").innerHTML=valo37;
var valo38=
document.getElementById("v38").innerHTML=valo38;
var valo39=
document.getElementById("v39").innerHTML=valo39;
var valo40=
document.getElementById("v40").innerHTML=valo40;
var valo41=
document.getElementById("v41").innerHTML=valo41;
var valo42=
document.getElementById("v42").innerHTML=valo42;
var valo43=
document.getElementById("v43").innerHTML=valo43;
var valo44=
document.getElementById("v44").innerHTML=valo44;