var valo72=
document.getElementById("v72").innerHTML=valo72;
var valo73=
document.getElementById("v73").innerHTML=valo73;
var valo74=
document.getElementById("v74").innerHTML=valo74;
var valo75=
document.getElementById("v75").innerHTML=valo75;
var valo76=
document.getElementById("v76").innerHTML=valo76;
var valo77=
document.getElementById("v77").innerHTML=valo77;
var valo78=
document.getElementById("v78").innerHTML=valo78;
var valo79=
document.getElementById("v79").innerHTML=valo79;
var valo80=
document.getElementById("v80").innerHTML=valo80;