var pg0='foto-anc/KWAI.jpg'
document.getElementById("foto1").src = pg0;
var pg1= pg0
document.getElementById("foto2").src = pg1;
var pg2=pg1
document.getElementById("foto3").src = pg2;
//var valo4=0
//document.getElementById("v4").innerHTML=valo4;
//var valo5=0
//document.getElementById("v5").innerHTML=valo5;
//var valo6=0
//document.getElementById("v6").innerHTML=valo6;
//var valo7=0
//document.getElementById("v7").innerHTML=valo7;
//var valo8=0
//document.getElementById("v8").innerHTML=valo8;
//var valo9=0
//document.getElementById("v9").innerHTML=valo9;